### PR TITLE
Optimize _uplevel_caller to avoid creating an AV every loop

### PR DESCRIPTION
**Pull request by bdraco**
This made Sub::Uplevel about ~40% faster for me.

### CODE REVIEW

**Comment by jkeenan** [comment]
This looks very good.  How did you benchmark the improvements?  Also -- question from someone unfamiliar with perlguts -- how did you identify the specific guts-level improvement that came from this refactoring?

**Comment by xdg** [comment]
Looks good to me.

**Comment by haarg** [comment]
Avoiding the array seems like a good idea, but changing the scope of the variable doesn't make much sense.  Does elevating the variable actually make a difference in performance?

**Comment by bdraco** [comment]
@jkeenan 

Found using NYTProf on tests that use lots of Test::Exception.

Benchmark below

```


              Rate my_inner_av my_outer_av    my_inner    my_outer
my_inner_av  210/s          --         -7%        -78%        -81%
my_outer_av  226/s          8%          --        -76%        -80%
my_inner     953/s        354%        322%          --        -15%
my_outer    1119/s        433%        395%         17%          --

use Benchmark ();

Benchmark::cmpthese(
    50000,
    {
        'my_inner_av' => sub {
            for ( 0 .. 5000 ) {
                my @test_var = CORE::caller();
            }
        },
        'my_outer_av' => sub {
            my @test_var;
            for ( 0 .. 5000 ) {
                @test_var = CORE::caller();
            }
        },
        'my_outer' => sub {
            my $test_var;
            for ( 0 .. 5000 ) {
                $test_var = scalar CORE::caller();
            }
        },
        'my_inner' => sub {
            for ( 0 .. 5000 ) {
                my $test_var = scalar CORE::caller();
            }
        },

    }
);

```

**Pull request merged**
